DROP TABLE IF EXISTS points;
DROP TABLE IF EXISTS redeem_queue;

CREATE TABLE points (
  id TEXT PRIMARY KEY,
  name TEXT,
  points INTEGER
);

CREATE TABLE counters (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL
  count INTEGER NOT NULL
);

CREATE TABLE redeem_queue (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  redeem TEXT NOT NULL,
  redeemer_id TEXT NOT NULL,
  note TEXT,
  FOREIGN KEY (redeemer_id) REFERENCES points (id)
);